[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/socket.io/*"
  to = "http://localhost:3000/socket.io/:splat"
  status = 200
  force = true